version: '3.8'

services:
  seed:
    build:
      context: .
      dockerfile: Dockerfile.simple.dev
    volumes:
      - ./client:/app/client
      - ./server:/app/server
      - ./shared:/app/shared
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./drizzle.config.ts:/app/drizzle.config.ts
      - ./pathfix.js:/app/pathfix.js
    environment:
      - NODE_ENV=development
      # Use your serverless database URL here (will be passed from host environment)
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=dev_session_secret
    # Command to seed the database
    command: >
      sh -c "
        echo 'Pushing database schema...' &&
        npm run db:push &&
        echo 'Seeding database...' &&
        npm run db:seed &&
        echo 'Database seeding completed!' &&
        exit 0
      "
